version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  app:
    ports:
      - "3007:3000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      MONGODB_URL: mongodb://mongodb:27017/staty
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always
    volumes:
      - ./:/app

volumes:
  mongo-data:

networks:
  app-network: